app:
  name: 'course_project'
  version: 'v0.1'

logger:
  level: 'info'
  file: 'out.log'

auth:
  signingKey: "course"
  accessTokenTTL: 100m
  refreshTokenTTL: 120h

http:
  port: 8081

database:
  postgres:
    host: 'localhost'
    port: 5432
    user: 'postgres'
    password: 'admin'
    database: 'course'
  mongodb:
    uri: 'mongodb://localhost:27017'
    database: 'course'
    bucket: 'photos'